server:
  port: 8081

spring:
  rabbitmq:
    host: 192.168.5.5
    port: 5672
    virtual-host: test
    username: admin
    password: 123456
    listener:
      direct:
        prefetch: 1
    #消息生产者发送确认配置
    publisher-confirm-type: correlated #消息->交换机确认
    publisher-returns: true #消息 交换机->队列确认回调ConfirmCallback
    template:
      mandatory: true #消息 交换机->队列失败回调ReturnsCallback

logging:
  level:
    root: info
