spring:
  data:
    redis:
      # master密码
      password: 123456
      #redis 哨兵配置
      sentinel:
        master: mymaster
        nodes:
          - 192.168.5.5:27001
          - 192.168.5.5:27002
          - 192.168.5.5:27003

logging:
  level:
    io.lettuce.core: debug

  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS