spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.5:3306/demo_activiti
    username: root
    password: 123456
    #连接池配置
    druid:
      #初始连接数
      initial-size: 50
      #最小空闲连接数
      min-idle: 30
      #最大活跃连接数
      max-active: 200
      #获取连接的最大等待时间
      max-wait: 30000
  #activiti工作流
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:process/*
    process-definition-location-suffixes: .bpmn20.xml

mybatis-plus:
  type-aliases-package: com.demo.mp.entity # 别名扫描名
  mapper-locations: classpath:mapper/**/*.xml # Mapper.xml扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
    map-underscore-to-camel-case: true # 开启下划线、驼峰映射
    cache-enabled: true # 开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类型转换
  global-config:
    db-config:
      #id-type: assign_id # id生成策略：雪花算法
      id-type: auto
      update-strategy: not_null # 更新策略：只更新非空字段
logging:
  level:
    sql: info