server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.5:3306/demo_cloud
    username: root
    password: 123456

mybatis-plus:
  type-aliases-package: com.demo.mp.entity # 别名扫描名
  mapper-locations: classpath:mapper/*.xml # Mapper.xml扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
    map-underscore-to-camel-case: true # 开启下划线、驼峰映射
    cache-enabled: true # 开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类型转换
  global-config:
    db-config:
      #id-type: assign_id # id生成策略：雪花算法
      id-type: auto
      update-strategy: not_null # 更新策略：只更新非空字段

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

