server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/order/**
        - id: service-user
          uri: lb://service-user
          #路由断言工厂
          predicates:
            - Path=/user/**

jwt:
  location:
  password:
  tokenTTL: 30
  auth:
    excludePaths:
      - /user/login
      - /items/**
      - /search/**
