server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.5:3306/demo_mybatis
    username: root
    password: 123456
  redis:
    host: 192.168.5.5
    port: 7001
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

logging:
  request-log-timeout: 1000 #日志输出警告-请求超时时间

mybatis-plus:
  type-aliases-package: com.demo.mp.entity # 别名扫描名
  mapper-locations: classpath:mapper/*.xml # Mapper.xml扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
    map-underscore-to-camel-case: true # 开启下划线、驼峰映射
    cache-enabled: true # 开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类型转换
  global-config:
    db-config:
      #id-type: assign_id # id生成策略：雪花算法
      id-type: auto
      update-strategy: not_null # 更新策略：只更新非空字段